### ISSUE TITLE
ServiceAlreadyExists exception raises when trying to reconnect service

### ISSUE THREAD

**Issue by felipeZ** [MD-Studio/cerise-mdstudio-das5#1]
I try to run the the [gromacs example]( https://github.com/MD-Studio/cerise-mdstudio-das5/blob/develop/examples/run_gromacs.py) Everything seemed to go well until  I press `control-C`
while waiting for the clsuter to finish the job, then I relaunched the script and got the following exception:
```python
(mdstudio) user@server:~/WorkbenchPython/Cerise_examples/cerise-mdstudio-das5/examples$ python run_gromacs.py 
^CTraceback (most recent call last):
  File "run_gromacs.py", line 48, in <module>
    sleep(10)
KeyboardInterrupt
(mdstudio) user@server:~/WorkbenchPython/Cerise_examples/cerise-mdstudio-das5/examples$ python run_gromacs.py 
Traceback (most recent call last):
  File "run_gromacs.py", line 11, in <module>
    '123abc')
  File "/home/user/miniconda2/envs/mdstudio/lib/python2.7/site-packages/cerise_client/service.py", line 91, in create_se
rvice
    raise errors.ServiceAlreadyExists()
cerise_client.errors.ServiceAlreadyExists
```
What has gone wrong?

**Comment by felipeZ** [comment]
The service is already created and running in a docker container and therefore can be query as : 
```python
 srv = cs.get_service('cerise-mdstudio-das5-myuser', 29593) 
```

Then we can get the job data as:

```python
 job = srv.get_job_by_id('599d7de17b9d468fac34f6ab2843a851')
```
