### ISSUE TITLE
Energy step fails due to too old numpy

### ISSUE THREAD

**Issue by LourensVeen** [MD-Studio/cerise-mdstudio-das5#10]
Here's the error message:
```
Traceback (most recent call last):
  File "/home/lveen/.cerise/api/files/mdstudio/bin/getEnergies.py", line 30, in <module>
    from panedr import edr_to_df
  File "/home/lveen/.local/lib/python2.7/site-packages/panedr/__init__.py", line 3, in <module>
    from .panedr import *
  File "/home/lveen/.local/lib/python2.7/site-packages/panedr/panedr.py", line 48, in <module>
    import pandas
  File "/home/lveen/.local/lib/python2.7/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat.numpy import *
  File "/home/lveen/.local/lib/python2.7/site-packages/pandas/compat/numpy/__init__.py", line 24, in <module>
    'this pandas version'.format(_np_version))
ImportError: this version of pandas is incompatible with numpy < 1.9.0
your numpy version is 1.7.1.
Please upgrade numpy to >= 1.9.0 to use this pandas version
```

**Comment by felipeZ** [comment]
fixed with #11
